### ISSUE TITLE
Make this app more presentable

### ISSUE THREAD

**Issue by arteevraina** [arteevraina/Music-App#1]
Try to improve its Html and Css files

**Comment by 1880akshay** [comment]
Hi! I want to work on this issue and can make this app look even more presentable.

**Comment by arteevraina** [comment]
@1880akshay  yeah sure feel free to contribute.

**Comment by aadhar54** [comment]
Hello @arteevraina .I would like to work on this issue .

**Comment by arteevraina** [comment]
@aadhar54 your contributions are welcome

**Comment by gaumo62** [comment]
Hey I would like to work on this issue

**Comment by Ayush-KS** [comment]
Hello!
This is going to be my first ever contribution. I have made a static music player before and would really like to work on this project!
