### ISSUE TITLE
The readme files lacks proper description

### ISSUE THREAD

**Issue by ujjawal01** [arteevraina/Music-App#11]
I want to add working image and proper steps to run it on localhost.

**Comment by ExpressHermes** [comment]
I would like to work on this issue

**Comment by Muskan-Mangal** [comment]
Hey @arteevraina ! I just sent a PR making the steps for running it more clear. It would be a great push for a first time contributor if you could review and merge it please :)

![Screenshot from 2019-12-26 16-12-56](https://user-images.githubusercontent.com/33172345/71472881-b9c19400-27fa-11ea-9b7d-5e3f2330a793.png)

**Comment by arteevraina** [comment]
@Muskan-Mangal Keep Contributing! Good Luck!

**Comment by Muskan-Mangal** [comment]
I think this issue should be closed @arteevraina. It's readable and understandable now. Otherwise any other newbie would come and will try make changes to the already presentable README instead of other issues as this looks an easier catch.
