### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by Muskan-Mangal** [arteevraina/Music-App#18]
There is a black space if we scroll the page a bit and the UI is not smooth and flowy at all.

**Comment by deepanshu368** [comment]
Can i adress this issue  plz?

**Comment by Muskan-Mangal** [comment]
Yeah !
Deadline has come and no one has addressed the issue.

**Comment by deepanshu368** [comment]
ok i have done it almost 50%
rest i would do as soon as possible

**Comment by deepanshu368** [comment]
plz check my pull request
