### ISSUE TITLE
Add more sounds

### ISSUE THREAD

**Issue by arteevraina** [arteevraina/Music-App#2]

**Comment by bitlucky** [comment]
Hye! I can add some more sounds using Keyboard.

**Comment by 1880akshay** [comment]
Hi! I want to work on this issue.

**Comment by arteevraina** [comment]
@bitlucky Yes u can work on this issue

**Comment by arteevraina** [comment]
@1880akshay feel free to contribute

**Comment by bitlucky** [comment]
> @bitlucky Yes u can work on this issue

Check out the pull request that i have created.
