### ISSUE TITLE
add animations on pressing key

### ISSUE THREAD

**Issue by arteevraina** [arteevraina/Music-App#5]
Just like animations appear when we click on pads using mouse the same animations should appear on pressing keys.

**Comment by sgpritam** [comment]
Please explain the codebase @arteevraina

**Comment by 1880akshay** [comment]
Can I use JQuery for implementing various animations?

**Comment by arteevraina** [comment]
@1880akshay go ahead!

**Comment by arteevraina** [comment]
@sgpritam Front-end is designed using HTML and CSS and functionality has been added using pure javascript.

**Comment by Shardul555** [comment]
@arteevraina  Can you tell me current progress in this issue.
I am a beginner in open source and want to contribute in this issue.

**Comment by arteevraina** [comment]
@Shardul555  currently sounds are produced on pressing keys

**Comment by Shardul555** [comment]
Hey @arteevraina  Can you please explain what is function() in  pad.addEventListener("click", function(){}
used as argument here. I am not able to find out proper work of this function and also unable to find its function definition anywhere.
